config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout
  get '/register', to: 'registration#new', as: :register
  post '/register', to: 'registration#create', as: :create_registration

  get '/', to: 'projects#index'

  resources :registration, only: [:create]
  resources :records
  resources :issues
  resources :projects
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :issue

  validates :id, uniqueness: true
  validates :name, uniqueness: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authorized?, only: [:edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = ProjectDecorator.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params).decorate

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = ProjectDecorator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(project, class: 'uk-form-horizontal uk-margin-large') do |f| %>
  <% if project.errors.any? %>
    <%= render partial: 'share/alert', locals:
        { error_count: project.errors.count,
          messages: project.errors.full_messages } %>
  <% end %>

  <div class="uk-margin field">
    <%= f.label :name, class: 'uk-form-label' %>
    <div class="uk-form-controls">
      <%= f.text_field :name, class: 'uk-input' %>
    </div>
  </div>

  <div class="uk-margin field">
    <%= f.label :description, class: 'uk-form-label' %>
    <div class="uk-form-controls">
      <%= f.text_area :description, class: 'uk-input' %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit 'Save', class: 'uk-button uk-button-default' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing "<%= @project.name %>"</h1>

<%= render 'form', project: @project %>

<div class="uk-clearfix">
  <div class="uk-float-right">
    <%= link_to 'Back', projects_path, class: 'uk-button uk-button-default' %>
  </div>
  <div class="uk-float-right">
    <%= link_to 'Show', @project, class: 'uk-button uk-button-default' %>
  </div>
</div>

app/views/projects/index.html.erb
<%= render partial: 'share/notice', locals: { notice: notice } %>

<div class="uk-clearfix">
  <% if current_user.admin? %>
    <div class="uk-float-right">
      <%= link_to '',
          new_project_path,
          class: 'uk-icon-link', 'uk-icon': 'icon: plus; ratio: 2' %>
    </div>
  <% end %>
  <div class="uk-float-left">
    <h1>Projects</h1>
  </div>
</div>

<ul class="uk-list uk-list-divider">
  <% @projects.each do |project| %>
    <li class="uk-card uk-card-default uk-card-body">
      <div class="uk-clearfix uk-width-1-1">
        <div class="uk-float-right">
          <%= project.edit_link %>
        </div>
        <div class="uk-float-left">
          <%= link_to project.name, project, class: 'uk-h3' %>
        </div>
      </div>
      <div class="uk-width-1-1 uk-margin-remove">
        <%= project.description %>
      </div>
      <div class="uk-width-1-1 uk-margin-top">
        <%= project.progress %>
      </div>
    </li>
  <% end %>
</ul>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<div class="uk-clearfix">
  <div class="uk-float-right uk-margin" uk-margin>
    <%= link_to 'Back', projects_path, class: 'uk-button uk-button-default' %>
  </div>
</div>

app/views/projects/show.html.erb
<%= render partial: 'share/notice', locals: { notice: notice } %>

<div class="uk-clearfix">
  <div class="uk-float-right">
    <%= @project.edit_link %>
    <%= @project.destroy_link %>
  </div>
  <div class="uk-float-left">
    <h1><%= @project.name %></h1>
  </div>
</div>

<div class="uk-card uk-card-default uk-card-body">
  <p>
    <strong>Description:</strong>
    <%= @project.description %>
  </p>
  <p>
    <strong>Issues:</strong>
    <%= @project.issue.count %>
  </p>
  <div class="uk-width-1-1 uk-margin-top">
    <%= @project.progress %>
  </div>
</div>
<%= @project.issues_tag %>
<div class="uk-card uk-card-default uk-card-body uk-margin-top uk-padding-remove">
  <ul class="uk-list uk-list-divider">
    <% @project.issue.each do |issue| %>
      <li class="<%= issue.success %> uk-padding-small">
        <div class="uk-clearfix uk-width-1-1">
          <div class="uk-float-right">
            <%= issue.edit_link %>
          </div>
          <div class="uk-float-left">
            <%= link_to issue.compact_name, issue, class: 'uk-h3' %>
          </div>
        </div>
        <div class="uk-clearfix uk-width-1-1">
          <div class="uk-float-right">
            <strong>ETA: </strong><%= issue.estimated_time %>
          </div>
          <div class="uk-float-left">
            <%= issue.description %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>