config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout
  get '/register', to: 'registration#new', as: :register
  post '/register', to: 'registration#create', as: :create_registration

  get '/', to: 'projects#index'

  resources :registration, only: [:create]
  resources :records
  resources :issues
  resources :projects
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :require_login

  def current_user
    @current_user ||= User.find(session[:user_id])
  end

  def authorized?
    redirect_to :back unless current_user.admin?
  end

  def require_logout
    redirect_to projects_path if session[:user_id]
  end

  private
    def require_login
      redirect_to login_path unless session[:user_id]
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    @current_user ||= User.find(session[:user_id])
  end

end

app/views/application/_navbar.html.erb
<nav class="uk-navbar-container" uk-navbar>
  <div class="uk-navbar-left">
    <%= link_to 'WorkHours', projects_path, class: 'uk-navbar-item uk-logo uk-margin-left' %>
    <ul class="uk-navbar-nav">
      <li><%= link_to 'Projects', projects_path %></li>
      <li><%= link_to 'Issues', issues_path %></li>
      <li><%= link_to 'Records', records_path %></li>
      <% if current_user.admin? %>
        <li><%= link_to 'Users', users_path %></li>
      <% end %>
    </ul>
  </div>
  <div class="uk-navbar-right">
    <ul class="uk-navbar-nav uk-margin-right">
      <li><%= link_to 'Add record', new_record_path %></li>
      <li>
        <a href="#" uk-icon="chevron-down"><%= current_user.name %></a>
        <div class="uk-navbar-dropdown">
          <ul class="uk-nav uk-navbar-dropdown-nav">
            <li><%= link_to 'Edit', edit_user_path(current_user) %></li>
            <li><%= link_to 'Logout', logout_path %></li>
          </ul>
        </div>
      </li>
    </ul>
  </div>
</nav>